name: Terraform Automation

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # Step 3: Initialize Terraform (downloads provider plugins and sets up backend)
      - name: Initialize Terraform
        run: terraform init

      # Step 4: Validate Terraform configuration (checks for syntax errors)
      - name: Validate Terraform configuration
        run: terraform validate

      # Step 5: Terraform Plan (shows the changes that Terraform will make)
      - name: Plan Terraform changes
        run: terraform plan

      # Step 6: Apply Terraform changes (apply infrastructure changes automatically)
      - name: Apply Terraform changes
        run: terraform apply -auto-approve
